# Generated by Django 6.0.6 on 2026-07-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitFetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
    ]
